### ISSUE TITLE
Referral status not showing

### ISSUE THREAD

**Issue by elboga-ai** [BladeBTC/BladeBTC#68]
I've referred 3 people with my link and status is still not showing up, it says no referrals

**Comment by nicelife90** [comment]
The referral is handle by the start command. Look to this command.

Le 14 août 2019 20 h 16, elboga-ai <notifications@github.com> a écrit :

I've referred 3 people with my link and status is still not showing up, it says no referrals

**Comment by BladeBTC** [comment]
The referral system is working I tested it!
