### ISSUE TITLE
Bot, mysql, GUI

### ISSUE THREAD

**Issue by Deltwin** [BladeBTC/BladeBTC#72]
Hi, i edit the file StartCommand.php message but nothing appened what i need to do?

2) Mysql: I haven't a database with the same ip of the vps but i have a web site i can set the database to another site?

3) i edit the file for gui (the name and others) but the name is the same.... I try to open the file from vps and the code is edited but idk...

**Comment by nicelife90** [comment]
hi to setup database to another server you will need to install database manually and open remote connections.

Le 2 sept. 2019 18 h 59, Deltwin <notifications@github.com> a écrit :

Hi, i edit the file StartCommand.php message but nothing appened what i need to do?

  1.  Mysql: I haven't a database with the same ip of the vps but i have a web site i can set the database to another site?

**Comment by Deltwin** [comment]
I need to edit the files database on the vps? I mean database.php

And please help with files what i need to do text of the files don't want to change
