### ISSUE TITLE
Buy DB

### ISSUE THREAD

**Issue by ILikeTG** [BladeBTC/BladeBTC#75]
HI! Thanks for sharing this fantastic source!

What type of DataBase i need to buy: ?

MariaDB 10.2 / 10.1
MySql 5.7
PosteGreSql 10 / 11 / 9.6
Redis 3.2 / 4.0

And How many ram?

512 MB / 1 GB RAM

Thanks, Bye.

**Comment by nicelife90** [comment]
MySQL or MariaDB Will work I prefer MariaDB.

Le 6 sept. 2019 13 h 24, ILikeTG <notifications@github.com> a écrit :

HI! Thanks for sharing this fantastic source!

What type of DataBase i need to buy: ?

MariaDB 10.2 / 10.1
MySql 5.7
PosteGreSql 10 / 11 / 9.6
Redis 3.2 / 4.0

Thanks, Bye.

**Comment by ILikeTG** [comment]
Ok thanks bye.
