### ISSUE TITLE
SQLSTATE[HY000] [1049] Unknown database 'telegram_bot'

### ISSUE THREAD

**Issue by mantoayo** [BladeBTC/BladeBTC#79]
I installed bladebtc on gcloud ubuntu, I can login to /phpmyadmin but if I try login to /gui admin panel it shows me this error :
SQLSTATE[HY000] [1049] Unknown database 'telegram_bot'
I try login and pass from /phmmyadmin and default : bladebtc but not work..still the same error.
can You help me?

**Comment by Deltwin** [comment]
.... Formact your VPS Ubuntu. After install:
Apache2
Php7
and see on youtube how to set properly a vps for web hosting site and how to install phpmyadmin.

**Comment by nicelife90** [comment]
Look in phpmyadmin if you could find telegram_bot database. if not this is probably because you don't fill the install script question with the rights information.

**Comment by cryptoknight-dev** [comment]
Easy just go yourip/phpmyadmin and import the sql database

**Comment by mantoayo** [comment]
Manually importing base.sql helped me. Thank you for your help
