### ISSUE TITLE
Certificate SSL

### ISSUE THREAD

**Issue by Deltwin** [BladeBTC/BladeBTC#80]
Hi you can send me the code for install the certificate please?

**Comment by Clexcorg** [comment]
Normally you should get ssl certificate from your host or contact them on the procedures to install an external one.

**Comment by nicelife90** [comment]
The install script get a certificate from let's encrypt automatically using certbot. This process will fail if you don't follow all the install instructions. The main reason causing failure is when port 80, 443 is not open and when your domain name or dynamic dns name is not  resolving publicly to your server.

**Comment by Deltwin** [comment]
ok thx :)
