### ISSUE TITLE
Issue - No Users Showing In Dashboard

### ISSUE THREAD

**Issue by Signalyze** [BladeBTC/BladeBTC#81]
Resolved

**Comment by Signalyze** [comment]
I can see in DB I can see user account and all correct value only issue is nothing show's in dash for users. 

I noticed that in the DB we have telegram_username 

> | id | telegram_username 

But dash it looking for 

```
SELECT access_level FROM gui_module WHERE name = 'telegram-users'1.96ms18.54KB0BladeBTC
UPDATE gui_module SET visits = visits + 1, last_visit = NOW() WHERE name = 'telegram-users'
```
Thank you for uploading this project I look forward to your response.

**Comment by mantoayo** [comment]
i have the same problem

**Comment by BladeBTC** [comment]
User dashboard is not working at this time!
